### ISSUE TITLE
Test-Issue for: Issue with checklist.

### ISSUE THREAD

**Issue by ojtanner** [ojtanner/VLC_Youtube_Downloader#2]
This issue is created to test out the feature of checklists.

**Comment by ojtanner** [comment]
- [x] Create Issue with tasklist.
- [ ] Write down some unnecessary tasks.
- [ ] Check if it works.
